name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVBOX_HOST }}
          username: ${{ secrets.DEVBOX_USER }}
          key: ${{ secrets.DEVBOX_SSH_KEY }}
          port: ${{ secrets.DEVBOX_SSH_PORT }}
          script: |
            APP_PATH="projects/${{ github.event.repository.name }}"
            mkdir -p $APP_PATH
            cd $APP_PATH
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git pull origin main
            fi
            docker-compose up -d --build ${{ github.event.repository.name }}
