name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVBOX_HOST }}
          username: ${{ secrets.DEVBOX_USER }}
          key: ${{ secrets.DEVBOX_SSH_KEY }}
          port: ${{ secrets.DEVBOX_SSH_PORT }}
          script: |
            export PATH=$PATH:$(npm bin -g)
            APP_PATH="$HOME/projects/${{ github.event.repository.name }}"
            if [ ! -d "$APP_PATH" ]; then
              mkdir -p $APP_PATH
              git clone https://github.com/${{ github.repository }}.git $APP_PATH
            fi

            cd $APP_PATH
            git pull origin main
            npm install --production

            npx -p @nestjs/cli nest build
            npx -p pm2 pm2 restart ${{ github.event.repository.name }} || \
            npx -p pm2 pm2 start dist/main.js --name ${{ github.event.repository.name }}
            npx -p pm2 pm2 save
